security:
  oauth2:
    client:
      client-id: ENC(XFuQfJv0dFvEGLpkNm/+lA==)
      client-secret: ENC(XFuQfJv0dFvEGLpkNm/+lA==)
      scope: server

spring:
  jpa:
    hibernate:
      #     更新或者创建数据表结构
      ddl-auto: update
    #    控制台显示SQL
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@192.168.10.200:1521:XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: scf
    password: 123456
  jms:
    pub-sub-domain: true
  activemq:
    broker-url: tcp://192.168.10.200:61616
    user: admin
    password: admin
    in-memory: false
    packages:
      trust-all: true
    pool:
      enabled: true
      max-connections: 5

# mybaits 模块配置
mybatis-plus:
  typeAliasesPackage: com.cysoft.scf.demo.biz.entity


scf:
  exception:
    handler: com.cysoft.scf.common.core.exception.handler.ExceptionMessageHander
  message:
    jms:
      username: weblogic
      password: welcome1
      url: t3://192.168.10.111:7001
