## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(XFuQfJv0dFvEGLpkNm/+lA==)
      client-secret: ENC(XFuQfJv0dFvEGLpkNm/+lA==)
      scope: server

# 数据源
spring:
#  jms:
#    pub-sub-domain: true
#  activemq:
#    broker-url: tcp://192.168.10.200:61616
#    user: admin
#    password: admin
#    in-memory: false
#    packages:
#      trust-all: true
#    pool:
#      enabled: true
#      max-connections: 5

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    driver-class-name: oracle.jdbc.OracleDriver
    username: scf
    password: 123456

# mybaits 模块配置
mybatis-plus:
  typeAliasesPackage: com.cysoft.scf.admin.api.entity

# swagger相关配置,覆盖全局配置
swagger:
  authorization:
    authorization-scope-list:
      - scope: 'server'
        description: 'server all'
      - scope: 'read'
        description: 'read all'
      - scope: 'write'
        description: 'access all'
