# 数据源
spring:
#  jms:
#    pub-sub-domain: true
#  activemq:
#    broker-url: tcp://192.168.10.200:61616
#    user: admin
#    password: admin
#    in-memory: false
#    packages:
#      trust-all: true
#    pool:
#      enabled: true
#      max-connections: 5
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    driver-class-name: oracle.jdbc.OracleDriver
    username: scf
    password: 123456
